#!/bin/bash
# ------------------------------------------------------------------------------
CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2019-2022; BSD License"
CEN_TITLE=$"Create a centauri-bash-lib user script from a template"

# Import the bash library, set name and version
PATH+=":${0%/*}" . _centauri_bash_lib -a -d -r -s -t -y "$0" "0.10:1" || exit 2

# Data
CEN_RUN_MIN_ARGS=1              # min arg count, see arguments()
CEN_RUN_MAX_ARGS=1              # max arg count

CEN_OPT_AUTHOR=                 # see --author
CEN_OPT_CHECK=                  # see --check
CEN_OPT_DESCR=                  # see --descr
CEN_OPT_LICENSE=                # see --license
CEN_OPT_NOCONF=                 # see --noconf
CEN_OPT_OPTION=()               # see --option
CEN_OPT_SHELL=                  # see --shell
CEN_OPT_TEMPLATE=               # see --template

DAT_AUTHOR=                     # config file data...
DAT_LICENSE=
DAT_SHELL=

DAT_FILE=                       # output file
DAT_REP_FROM=                   # replace template text
DAT_REP_TO=
DAT_TEMPLATE="$CEN_TOOLS/templates"
DAT_NAME_REG=
DAT_NAME_DEF='hello'
declare -A DAT_NAME_MAP

# ------------------------------------------------------------------------------
# Get template information: [-h]
# ------------------------------------------------------------------------------
get_templates() {
    local _item _name
    for _item in "$DAT_TEMPLATE/centauri"[A-Z]* ; do
        [ -x "$_item" ] || continue
        _name="${_item##*centauri}" ; _name="${_name,,}"
        if [ -n "$1" ] ; then
            if ! system -q -a _info -- "$_item" --info detailed ; then
                _info="Using _centauri_bash_lib without main()"
            fi
            printf -v _item "%-12s  %s" "$_name" "$_info"
            usageset -t "$_item"
        else
            [ -n "$DAT_NAME_REG" ] && DAT_NAME_REG+='|'
            DAT_NAME_REG+="$_name"
            DAT_NAME_MAP["$_name"]="${_item##*/}"
        fi
    done

    if [ -e "$DAT_TEMPLATE/_custom_module_usr" ] ; then
        [ -n "$DAT_NAME_REG" ] && DAT_NAME_REG+='|'
        DAT_NAME_REG+='module'
        DAT_NAME_MAP["module"]='_custom_module_usr'
        [ -n "$1" ] && usageset -t "module        a custom library module"
    fi
}

# ------------------------------------------------------------------------------
# Create from template: <template>
# ------------------------------------------------------------------------------
do_create() {
    local _line _skip _year
    printf -v _year "%(%Y)T" -1                 # get current 4-digit year

    # define option variables
    for _line in "${CEN_OPT_OPTION[@]^^}" ; do
        _line="${_line//[!A-Z]/}"
        [ -n "$_line" ] && eval "$_line"=true
    done

    # copy template code
    while IFS= read -r _line ; do
        case "$_line" in
            \#!/*/bash*)    _line="#!$DAT_SHELL" ;;
            CEN_TITLE=*)    [ -n "$CEN_OPT_DESCR" ] &&
                                _line="CEN_TITLE=\$\"$CEN_OPT_DESCR\"" ;;
            CEN_LEGAL=*)    _line="CEN_LEGAL=\"$DAT_AUTHOR$_year; $DAT_LICENSE\"" ;;

            [A-Z]*=*\ *##########*)
                            _line="${_line%% ######*}"
                            eval "$_line" ; continue ;;
            if\ *\;\ then\ *###########*)
                            _line="${_line%%; then*}" ; _line="${_line#* }"
                            eval "$_line" && _skip= || _skip=1 ; continue ;;
            else\ *##########*)
                            [ -n "$_skip" ]  && _skip= || _skip=1 ; continue ;;
            fi\ *##########*)
                            _skip= ; continue ;;
        esac
        [ -n "$_skip" ] && continue
        [ -n "$DAT_REP_FROM" ] && _line="${_line//$DAT_REP_FROM/$DAT_REP_TO}"
        echo "$_line"
    done
    return 0
}

# ------------------------------------------------------------------------------
# Run shellcheck
# ------------------------------------------------------------------------------
do_check() {
    local warn
    [ -n "$CEN_OPT_SILENT" ] && warn='-Swarning'
    sysfind -f 'shellcheck'
    system -e -p -g 1 -z -- shellcheck -x -e 2128,2166,2178,2247 $warn -W0 -P"$CEN_LIBRARY" "$@"
    quit
}

# ------------------------------------------------------------------------------
# The one and only action
# ------------------------------------------------------------------------------
run() {
    [ -n "$CEN_OPT_CHECK" ] && do_check "$@"             # run shellcheck, no return
    local _tmpl _name="$1"
    [ -n "$DAT_NAME_REG" ] || get_templates
    _tmpl="${DAT_NAME_MAP["${CEN_OPT_TEMPLATE:-$DAT_NAME_DEF}"]}"
    if [ "$CEN_OPT_TEMPLATE" = 'module' ] ; then
        _name="_$1_module_usr"
        DAT_REP_FROM="${_tmpl##*/}" ; DAT_REP_TO="$_name"
    fi
    outfile -c -l -s DAT_FILE -- "$_name" || return      # does error handling

    serialize -q -r DAT_AUTHOR DAT_LICENSE DAT_SHELL     # caching ...
    [ "$CEN_OPT_SHELL" ] && DAT_SHELL="$CEN_OPT_SHELL"
    [ "${DAT_SHELL:--}" = '-' ] && DAT_SHELL="${CEN_PATHS[1]}/bash"
    [ -n "$CEN_OPT_AUTHOR"  ] && DAT_AUTHOR="$CEN_OPT_AUTHOR"
    [ "${DAT_AUTHOR:--}" = '-' ] && DAT_AUTHOR=$"anonymous"
    [ -n "$CEN_OPT_LICENSE" ] && DAT_LICENSE="$CEN_OPT_LICENSE"
    [ "${DAT_LICENSE:--}" = '-' ] && DAT_LICENSE=$"all rights reserved"
    [ -z "$CEN_OPT_NOCONF" ] && serialize -w DAT_AUTHOR DAT_LICENSE DAT_SHELL

    local _ihan _mesg=$"<copy from input>"
    message -a -m \
        "┃" $"Selected template:" "$_tmpl" "\n" \
        "┃" $"Short description:" "${CEN_OPT_DESCR:-$_mesg}" "\n" \
        "┃" $"Author           :" "$DAT_AUTHOR" "\n" \
        "┃" $"License          :" "$DAT_LICENSE" "\n" \
        "┃" $"Interpreter      :" "$DAT_SHELL" "\n" \
        "┃" $"Output path      :" "$DAT_FILE"
    confirm -a -y -- $"Do you want to continue" || return

    _tmpl="$CEN_TOOLS/templates/$_tmpl"
    redirect -v _ihan -i "$_tmpl" || return             # does error handling
    if [ "$DAT_FILE" != "/dev/stdout" ] ; then          # output to file ...
        remove -f -- "$DAT_FILE"
        attributes -c -m 775 -- "$DAT_FILE" || return
    fi
    dryrun "do_create <&$_ihan >'$DAT_FILE'" && return  # debug
    do_create <&"$_ihan" >>"$DAT_FILE" && quit -a $"Script created"
}

# ------------------------------------------------------------------------------
# option parsing: <option> <argument>
# ------------------------------------------------------------------------------
options() {
    case "$1" in

    '')         if [ -n "$CEN_OPT_CHECK" ] ; then
                    CEN_RUN_MAX_ARGS=+
                    [ -n "$CEN_OPT_NOCONF$CEN_OPT_OPTION$CEN_OPT_SHELL$CEN_OPT_TEMPLATE" ] &&
                        optarg - - -m "--check --noconf|--option|--shell|--template"
                fi
                ;;

    -A|--aut*)
        optarg 'author'   - -t ;;   # any text
    -C|--che*)
        optarg 'check'    -    ;;   # flag
    -D|--des*)
        optarg 'descr'    - -t ;;   # any text
    -L|--lic*)
        optarg 'license'  - -t ;;   # any text
    -N|--noc*)
        optarg 'noconf'   -    ;;   # flag
    -O|--opt*)
        optarg 'option'  [] -t ;;   # text array
    -S|--she*)
        optarg 'shell'    - -t ;;   # any text
    -T|--tem*)
        get_templates
        optarg 'template' - "($DAT_NAME_REG)" ;;
    esac
}

# ------------------------------------------------------------------------------
# print usage info
# ------------------------------------------------------------------------------
usage() {
    usageset -u "$CEN_NAME <option>... <script>   # "$"create a script" \
             -u "$CEN_NAME --no -                 # "$"show cached options" \
             -u - \
             -u "$CEN_TITLE."

    usageset -o - \
             -o "-A --author   <text> "$"set script author" \
             -o "-D --descr    <text> "$"short description of script" \
             -o "-L --license  <text> "$"set script license" \
             -o "-N --noconf          "$"don't modify config file" \
             -o "-O --option   <name> "$"select template option (repeatable)" \
             -o "-S --shell    <bash> "$"override interpreter path (shebang)" \
             -o "-T --template <tmpl> "$"choose template (default: $DAT_NAME_DEF)" \
             -o - \
             -o $"The values of --author and --license are cached."

    usageset -l $"arguments" \
             -t "<bash>          "$"any path, for example:"' /usr/bin/env bash' \
             -t "<name>          "$"option name, gets converted to uppercase" \
             -t "<text>          "$"any text not containing \";\" or \"-\" to reset" \
             -t "<tmpl>          "$"name of a template, see below"

    usageset -l $"templates" ; get_templates -h

    usageset -l $"examples" \
             -t "# "$"create script without 'main()' from centauriHello template" \
             -t "$CEN_NAME --shell='/usr/bin/env bash' myfolder/simple" \
             -t "" \
             -t "# "$"create script with 'action' syntax" \
             -t "$CEN_NAME --template=action mytool" \
             -t "" \
             -t "# "$"create script without demo code" \
             -t "$CEN_NAME --template=action --option=minimal mytool"
}

# ------------------------------------------------------------------------------
# Finally call the library to execute the script
# ------------------------------------------------------------------------------
main "$@" ; quit

# the end
